### ISSUE TITLE
I made a tiddlywiki version of the book using this repo, can I upload the file publicly on github ?

### ISSUE THREAD

**Issue by Telumire** [j9t/css-optimization-basics#6]
Hello ! 

All is said in the title. I manually copy/pasted the content of each markdown file into a tiddlywiki file and made some custom formatting with css. Am I allowed to share it (for free of course, with open source license and credits) ?

I totally understand if you dont want that, and in that case I will keep the file for myself.

**Comment by j9t** [comment]
Hi @Telumire—thanks for letting me know!

To provide clarity about the book’s license, I just put it under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). I believe this license to grant a lot of room—please have a look, perhaps your version is already compliant with it. (If it is—great! If not, I hope the license allows you to make the needed changes.)

**Comment by j9t** [comment]
Closing this one, but please let me know where you re-publish, or if there are any follow-up questions!
